steps:
- name: node
  entrypoint: npm
  args: ['install', 'test', 'run', 'build']
artifacts:
  objects:
    location: 'gs://war123/'
    paths: ['https://console.cloud.google.com/storage/browser/war123?project=cicd-276708']
